[build]
    command = "yarn build"
    functions = "functions"
    publish = "dist"

[build.environment]
    API_KEY = "7035c60c"

[dev]
    framework = "#custom"
    command = "yarn start"
    targetPort = 3000
    port = 5000
    publish = "dist"
    autoLaunch = false